version: "3"
services:
  db:
    build: ./go/docker/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gameshop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: mysqld
  app:
    build: ./go
    depends_on:
      - db
    ports:
      - "8080:8888"
    environment:
      MYSQL_DB_HOST: db
      MYSQL_DB: gameshop
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
volumes:
  mysql_data:
